pipeline {
    agent any

    tools {
        maven "maven"
    }

    stages {
        stage('Source') {
            steps {
                git branch: 'main', url: 'https://github.com/ramanujds/spring-boot'
            }
        }

        stage('Test'){
            steps{
                sh "mvn test"
            }
        }

        stage('Build'){
            steps{
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }


            post {

                success {

                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }

}