pipeline {
    agent any

    tools {
        maven "maven"
    }

    stages {
        stage('Source') {
            steps {
                git branch: 'main', url: 'https://github.com/ramanujds/spring-boot'
            }
        }

        stage('Test'){
            steps{
                sh "mvn test"
            }
        }

        stage('Build'){
            steps{
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }


            post {

                success {

                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('Build Docker Image') {
                    steps{
                        sh "docker build --platform linux/amd64 -t spring-boot:latest ."
                    }
                 }
        stage('Push Docker Image') {
            steps {
              withCredentials([string(credentialsId: 'dockerhub_pdw', variable: 'docker')]){
                        sh 'docker login -u ram1uj -p ${docker}'
                        sh 'docker tag spring-boot:latest ram1uj/spring-boot:latest'
                        sh 'docker push ram1uj/spring-boot:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker stop spring-boot || true'
                sh 'docker rm spring-boot || true'
                sh 'docker pull ram1uj/spring-boot:latest'
                sh 'docker run -d -p 5000:5000 --name spring-boot ram1uj/spring-boot:latest'
            }
        }

       }

 }

