apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-recipes-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: easy-recipes.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: easy-recipes
                port:
                  number: 80
