apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: ["","apps"] # "" indicates the core API group
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "watch", "list"]
